environment: /usr/bin/tclsh: No such file or directory
[I 2025-06-28 13:29:07.322 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-06-28 13:29:07.325 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-06-28 13:29:07.328 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-06-28 13:29:07.331 ServerApp] notebook | extension was successfully linked.
[I 2025-06-28 13:29:07.500 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-06-28 13:29:07.511 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-06-28 13:29:07.513 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-06-28 13:29:07.513 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-06-28 13:29:07.515 LabApp] JupyterLab extension loaded from /home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyterlab
[I 2025-06-28 13:29:07.515 LabApp] JupyterLab application directory is /home/santiagovasquez/miniconda3/envs/test_env/share/jupyter/lab
[I 2025-06-28 13:29:07.515 LabApp] Extension Manager is 'pypi'.
[I 2025-06-28 13:29:07.554 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-06-28 13:29:07.557 ServerApp] notebook | extension was successfully loaded.
[I 2025-06-28 13:29:07.557 ServerApp] The port 8888 is already in use, trying another port.
[I 2025-06-28 13:29:07.557 ServerApp] Serving notebooks from local directory: /home/santiagovasquez/odr_test/notebooks
[I 2025-06-28 13:29:07.557 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-06-28 13:29:07.557 ServerApp] http://deeplearning04:8889/tree?token=e4044db537297723aaea9bdb80f7ab4cbd75eb21c7ce0fe9
[I 2025-06-28 13:29:07.557 ServerApp]     http://127.0.0.1:8889/tree?token=e4044db537297723aaea9bdb80f7ab4cbd75eb21c7ce0fe9
[I 2025-06-28 13:29:07.557 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2025-06-28 13:29:07.559 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/santiagovasquez/.local/share/jupyter/runtime/jpserver-24969-open.html
    Or copy and paste one of these URLs:
        http://deeplearning04:8889/tree?token=e4044db537297723aaea9bdb80f7ab4cbd75eb21c7ce0fe9
        http://127.0.0.1:8889/tree?token=e4044db537297723aaea9bdb80f7ab4cbd75eb21c7ce0fe9
The latest version of Julia in the `release` channel is 1.11.5+0.x64.linux.gnu. You currently have `1.11.1+0.x64.linux.gnu` installed. Run:

  juliaup update

to install Julia 1.11.5+0.x64.linux.gnu and update the `release` channel to that version.
[I 2025-06-28 13:29:07.684 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2025-06-28 13:29:13.765 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:13.766 ServerApp] 403 GET /api/kernels/574fb6ea-6836-46f2-b7d7-98ab482b7ed5?1751128153762 (@172.30.6.160) 1.73ms referer=None
[I 2025-06-28 13:29:15.807 ServerApp] 302 GET / (@172.30.6.160) 0.83ms
[W 2025-06-28 13:29:15.807 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.808 ServerApp] 403 GET /api/kernels?1751128155801 (@172.30.6.160) 1.35ms referer=None
[W 2025-06-28 13:29:15.808 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.809 ServerApp] 403 GET /api/kernels?1751128155805 (@172.30.6.160) 1.79ms referer=None
[I 2025-06-28 13:29:15.809 ServerApp] 302 GET / (@172.30.6.160) 0.40ms
[I 2025-06-28 13:29:15.809 ServerApp] 302 GET / (@172.30.6.160) 0.39ms
[W 2025-06-28 13:29:15.810 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.810 ServerApp] 403 GET /api/kernelspecs?1751128155800 (@172.30.6.160) 0.96ms referer=None
[W 2025-06-28 13:29:15.811 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.811 ServerApp] 403 GET /api/sessions?1751128155806 (@172.30.6.160) 1.23ms referer=None
[I 2025-06-28 13:29:15.812 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.25ms
[I 2025-06-28 13:29:15.815 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.20ms
[I 2025-06-28 13:29:15.815 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.21ms
[I 2025-06-28 13:29:15.815 ServerApp] 302 GET / (@172.30.6.160) 0.19ms
[I 2025-06-28 13:29:15.830 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 1.03ms
[W 2025-06-28 13:29:15.831 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.831 ServerApp] 403 GET /api/kernelspecs?1751128155830 (@172.30.6.160) 0.49ms referer=None
[W 2025-06-28 13:29:15.833 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.833 ServerApp] 403 GET /api/kernelspecs?1751128155832 (@172.30.6.160) 0.47ms referer=None
[W 2025-06-28 13:29:15.834 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.835 ServerApp] 403 GET /api/kernelspecs?1751128155833 (@172.30.6.160) 0.49ms referer=None
[W 2025-06-28 13:29:15.841 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.841 ServerApp] 403 GET /api/kernels?1751128155830 (@172.30.6.160) 0.77ms referer=None
[W 2025-06-28 13:29:15.841 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.841 ServerApp] 403 GET /api/kernels?1751128155832 (@172.30.6.160) 1.06ms referer=None
[W 2025-06-28 13:29:15.842 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.843 ServerApp] 403 GET /api/sessions?1751128155836 (@172.30.6.160) 0.83ms referer=None
[W 2025-06-28 13:29:15.843 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.843 ServerApp] 403 GET /api/kernels?1751128155837 (@172.30.6.160) 1.14ms referer=None
[W 2025-06-28 13:29:15.844 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.844 ServerApp] 403 GET /api/kernels?1751128155838 (@172.30.6.160) 0.59ms referer=None
[W 2025-06-28 13:29:15.845 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.845 ServerApp] 403 GET /api/kernels?1751128155834 (@172.30.6.160) 0.81ms referer=None
[W 2025-06-28 13:29:15.845 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.845 ServerApp] 403 GET /api/kernels?1751128155836 (@172.30.6.160) 1.10ms referer=None
[W 2025-06-28 13:29:15.845 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.846 ServerApp] 403 GET /api/sessions?1751128155838 (@172.30.6.160) 1.39ms referer=None
[W 2025-06-28 13:29:15.847 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.848 ServerApp] 403 GET /api/kernelspecs?1751128155847 (@172.30.6.160) 0.45ms referer=None
[W 2025-06-28 13:29:15.848 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.848 ServerApp] 403 GET /api/sessions?1751128155839 (@172.30.6.160) 0.46ms referer=None
[W 2025-06-28 13:29:15.854 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.855 ServerApp] 403 GET /api/kernelspecs?1751128155841 (@172.30.6.160) 0.47ms referer=None
[W 2025-06-28 13:29:15.855 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.855 ServerApp] 403 GET /api/kernelspecs?1751128155842 (@172.30.6.160) 0.48ms referer=None
[W 2025-06-28 13:29:15.856 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.856 ServerApp] 403 GET /api/kernelspecs?1751128155843 (@172.30.6.160) 0.86ms referer=None
[I 2025-06-28 13:29:15.857 ServerApp] 302 GET / (@172.30.6.160) 0.82ms
[W 2025-06-28 13:29:15.857 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.857 ServerApp] 403 GET /api/sessions?1751128155849 (@172.30.6.160) 1.06ms referer=None
[W 2025-06-28 13:29:15.857 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.858 ServerApp] 403 GET /api/kernels?1751128155848 (@172.30.6.160) 0.56ms referer=None
[W 2025-06-28 13:29:15.859 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.859 ServerApp] 403 GET /api/kernels?1751128155847 (@172.30.6.160) 1.06ms referer=None
[W 2025-06-28 13:29:15.859 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.859 ServerApp] 403 GET /api/kernelspecs?1751128155855 (@172.30.6.160) 1.30ms referer=None
[I 2025-06-28 13:29:15.859 ServerApp] 302 GET / (@172.30.6.160) 1.25ms
[I 2025-06-28 13:29:15.860 ServerApp] 302 GET / (@172.30.6.160) 1.19ms
[I 2025-06-28 13:29:15.860 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.21ms
[I 2025-06-28 13:29:15.864 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.35ms
[I 2025-06-28 13:29:15.864 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.35ms
[W 2025-06-28 13:29:15.868 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.869 ServerApp] 403 GET /api/kernelspecs?1751128155867 (@172.30.6.160) 0.87ms referer=None
[W 2025-06-28 13:29:15.872 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.872 ServerApp] 403 GET /api/kernelspecs?1751128155871 (@172.30.6.160) 0.47ms referer=None
[W 2025-06-28 13:29:15.873 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.873 ServerApp] 403 GET /api/kernels?1751128155868 (@172.30.6.160) 0.58ms referer=None
[W 2025-06-28 13:29:15.873 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.874 ServerApp] 403 GET /api/kernels?1751128155869 (@172.30.6.160) 0.87ms referer=None
[W 2025-06-28 13:29:15.877 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.878 ServerApp] 403 GET /api/kernelspecs?1751128155876 (@172.30.6.160) 0.58ms referer=None
[W 2025-06-28 13:29:15.878 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.878 ServerApp] 403 GET /api/sessions?1751128155870 (@172.30.6.160) 0.88ms referer=None
[W 2025-06-28 13:29:15.883 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.883 ServerApp] 403 GET /api/kernelspecs?1751128155873 (@172.30.6.160) 0.64ms referer=None
[W 2025-06-28 13:29:15.883 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.884 ServerApp] 403 GET /api/kernels?1751128155872 (@172.30.6.160) 0.48ms referer=None
[W 2025-06-28 13:29:15.884 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.884 ServerApp] 403 GET /api/kernels?1751128155874 (@172.30.6.160) 0.48ms referer=None
[W 2025-06-28 13:29:15.887 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.887 ServerApp] 403 GET /api/kernels?1751128155877 (@172.30.6.160) 0.49ms referer=None
[W 2025-06-28 13:29:15.887 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.887 ServerApp] 403 GET /api/sessions?1751128155874 (@172.30.6.160) 0.46ms referer=None
[W 2025-06-28 13:29:15.888 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.888 ServerApp] 403 GET /api/kernelspecs?1751128155878 (@172.30.6.160) 0.66ms referer=None
[W 2025-06-28 13:29:15.888 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.889 ServerApp] 403 GET /api/kernels?1751128155879 (@172.30.6.160) 0.95ms referer=None
[W 2025-06-28 13:29:15.889 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.889 ServerApp] 403 GET /api/sessions?1751128155879 (@172.30.6.160) 0.47ms referer=None
[W 2025-06-28 13:29:15.890 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:29:15.890 ServerApp] 403 GET /api/kernelspecs?1751128155883 (@172.30.6.160) 0.46ms referer=None
[I 2025-06-28 13:34:19.980 ServerApp] 302 GET / (@172.30.6.160) 0.31ms
[I 2025-06-28 13:34:19.982 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.29ms
[I 2025-06-28 13:34:20.821 ServerApp] 302 GET / (@172.30.6.160) 0.32ms
[I 2025-06-28 13:34:20.823 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.45ms
[I 2025-06-28 13:34:27.708 ServerApp] 302 GET / (@172.30.6.160) 0.29ms
[I 2025-06-28 13:34:27.710 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.26ms
[I 2025-06-28 13:34:27.752 ServerApp] Kernel started: 67e93076-d5db-4f0a-9316-6a69351ef46f
[I 2025-06-28 13:34:28.101 ServerApp] Connecting to kernel 67e93076-d5db-4f0a-9316-6a69351ef46f.
[W 2025-06-28 13:34:28.102 ServerApp] The websocket_ping_timeout (90000) cannot be longer than the websocket_ping_interval (30000).
    Setting websocket_ping_timeout=30000
[I 2025-06-28 13:34:28.184 ServerApp] 302 GET / (@172.30.6.160) 1.44ms
[I 2025-06-28 13:34:28.185 ServerApp] 302 GET / (@172.30.6.160) 1.32ms
[I 2025-06-28 13:34:28.185 ServerApp] 302 GET / (@172.30.6.160) 1.28ms
[I 2025-06-28 13:34:28.185 ServerApp] 302 GET / (@172.30.6.160) 1.40ms
[I 2025-06-28 13:34:28.196 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.22ms
[I 2025-06-28 13:34:28.196 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.22ms
[I 2025-06-28 13:34:28.197 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.34ms
[I 2025-06-28 13:34:28.197 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.39ms
[W 2025-06-28 13:34:28.219 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.220 ServerApp] 403 GET /api/kernelspecs?1751128468219 (@172.30.6.160) 0.58ms referer=None
[W 2025-06-28 13:34:28.220 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.220 ServerApp] 403 GET /api/kernels?1751128468219 (@172.30.6.160) 0.50ms referer=None
[W 2025-06-28 13:34:28.221 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.222 ServerApp] 403 GET /api/kernelspecs?1751128468220 (@172.30.6.160) 0.47ms referer=None
[W 2025-06-28 13:34:28.223 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.223 ServerApp] 403 GET /api/kernelspecs?1751128468222 (@172.30.6.160) 0.47ms referer=None
[W 2025-06-28 13:34:28.243 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.244 ServerApp] 403 GET /api/kernels?1751128468215 (@172.30.6.160) 0.64ms referer=None
[W 2025-06-28 13:34:28.244 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.244 ServerApp] 403 GET /api/kernelspecs?1751128468214 (@172.30.6.160) 0.62ms referer=None
[W 2025-06-28 13:34:28.244 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.245 ServerApp] 403 GET /api/kernels?1751128468216 (@172.30.6.160) 0.91ms referer=None
[W 2025-06-28 13:34:28.252 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.252 ServerApp] 403 GET /api/kernels?1751128468221 (@172.30.6.160) 0.52ms referer=None
[W 2025-06-28 13:34:28.253 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.253 ServerApp] 403 GET /api/kernels?1751128468226 (@172.30.6.160) 0.88ms referer=None
[W 2025-06-28 13:34:28.254 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.254 ServerApp] 403 GET /api/kernels?1751128468228 (@172.30.6.160) 1.16ms referer=None
[W 2025-06-28 13:34:28.254 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.254 ServerApp] 403 GET /api/sessions?1751128468229 (@172.30.6.160) 1.46ms referer=None
[W 2025-06-28 13:34:28.254 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.255 ServerApp] 403 GET /api/sessions?1751128468217 (@172.30.6.160) 1.78ms referer=None
[W 2025-06-28 13:34:28.256 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.257 ServerApp] 403 GET /api/kernels?1751128468223 (@172.30.6.160) 1.75ms referer=None
[W 2025-06-28 13:34:28.257 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.257 ServerApp] 403 GET /api/sessions?1751128468227 (@172.30.6.160) 2.06ms referer=None
[W 2025-06-28 13:34:28.257 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.257 ServerApp] 403 GET /api/kernels?1751128468230 (@172.30.6.160) 2.36ms referer=None
[W 2025-06-28 13:34:28.258 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.258 ServerApp] 403 GET /api/sessions?1751128468230 (@172.30.6.160) 2.64ms referer=None
[W 2025-06-28 13:34:28.260 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.261 ServerApp] 403 GET /api/kernelspecs?1751128468243 (@172.30.6.160) 0.64ms referer=None
[W 2025-06-28 13:34:28.261 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.261 ServerApp] 403 GET /api/kernelspecs?1751128468244 (@172.30.6.160) 0.96ms referer=None
[W 2025-06-28 13:34:28.261 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.262 ServerApp] 403 GET /api/kernelspecs?1751128468245 (@172.30.6.160) 0.49ms referer=None
[W 2025-06-28 13:34:28.274 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.274 ServerApp] 403 GET /api/kernelspecs?1751128468254 (@172.30.6.160) 0.53ms referer=None
[I 2025-06-28 13:34:28.275 ServerApp] 302 GET / (@172.30.6.160) 0.52ms
[I 2025-06-28 13:34:28.275 ServerApp] 302 GET / (@172.30.6.160) 0.52ms
[I 2025-06-28 13:34:28.275 ServerApp] 302 GET / (@172.30.6.160) 0.50ms
[I 2025-06-28 13:34:28.275 ServerApp] 302 GET / (@172.30.6.160) 0.50ms
[I 2025-06-28 13:34:28.289 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.32ms
[I 2025-06-28 13:34:28.289 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.37ms
[I 2025-06-28 13:34:28.289 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.19ms
[I 2025-06-28 13:34:28.290 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.25ms
[W 2025-06-28 13:34:28.308 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.309 ServerApp] 403 GET /api/kernelspecs?1751128468307 (@172.30.6.160) 0.50ms referer=None
[W 2025-06-28 13:34:28.309 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.309 ServerApp] 403 GET /api/kernels?1751128468308 (@172.30.6.160) 0.49ms referer=None
[W 2025-06-28 13:34:28.310 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.310 ServerApp] 403 GET /api/kernelspecs?1751128468309 (@172.30.6.160) 0.48ms referer=None
[W 2025-06-28 13:34:28.321 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.322 ServerApp] 403 GET /api/kernelspecs?1751128468320 (@172.30.6.160) 0.47ms referer=None
[W 2025-06-28 13:34:28.330 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.330 ServerApp] 403 GET /api/kernelspecs?1751128468305 (@172.30.6.160) 0.60ms referer=None
[W 2025-06-28 13:34:28.331 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.331 ServerApp] 403 GET /api/kernels?1751128468305 (@172.30.6.160) 0.53ms referer=None
[W 2025-06-28 13:34:28.332 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.332 ServerApp] 403 GET /api/kernels?1751128468310 (@172.30.6.160) 1.13ms referer=None
[W 2025-06-28 13:34:28.333 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.333 ServerApp] 403 GET /api/sessions?1751128468311 (@172.30.6.160) 1.42ms referer=None
[W 2025-06-28 13:34:28.333 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.333 ServerApp] 403 GET /api/kernels?1751128468311 (@172.30.6.160) 1.70ms referer=None
[W 2025-06-28 13:34:28.333 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.334 ServerApp] 403 GET /api/kernels?1751128468312 (@172.30.6.160) 1.96ms referer=None
[W 2025-06-28 13:34:28.334 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.334 ServerApp] 403 GET /api/sessions?1751128468313 (@172.30.6.160) 2.29ms referer=None
[W 2025-06-28 13:34:28.336 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.336 ServerApp] 403 GET /api/kernelspecs?1751128468331 (@172.30.6.160) 1.43ms referer=None
[W 2025-06-28 13:34:28.336 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.337 ServerApp] 403 GET /api/kernels?1751128468321 (@172.30.6.160) 1.70ms referer=None
[W 2025-06-28 13:34:28.337 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.337 ServerApp] 403 GET /api/kernels?1751128468322 (@172.30.6.160) 2.04ms referer=None
[W 2025-06-28 13:34:28.337 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.337 ServerApp] 403 GET /api/sessions?1751128468323 (@172.30.6.160) 2.38ms referer=None
[W 2025-06-28 13:34:28.338 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.338 ServerApp] 403 GET /api/kernelspecs?1751128468323 (@172.30.6.160) 2.69ms referer=None
[W 2025-06-28 13:34:28.338 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.338 ServerApp] 403 GET /api/kernelspecs?1751128468324 (@172.30.6.160) 3.03ms referer=None
[W 2025-06-28 13:34:28.339 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.339 ServerApp] 403 GET /api/kernels?1751128468325 (@172.30.6.160) 3.36ms referer=None
[W 2025-06-28 13:34:28.339 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.339 ServerApp] 403 GET /api/sessions?1751128468326 (@172.30.6.160) 3.70ms referer=None
[W 2025-06-28 13:34:28.340 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-28 13:34:28.340 ServerApp] 403 GET /api/kernelspecs?1751128468333 (@172.30.6.160) 0.60ms referer=None
[I 2025-06-28 17:16:56.208 ServerApp] Starting buffering for 67e93076-d5db-4f0a-9316-6a69351ef46f:08fce516-608f-4fbe-9c0d-143e83418d3f
[I 2025-06-29 17:36:13.833 ServerApp] 302 GET / (@172.30.6.160) 0.52ms
[I 2025-06-29 17:36:13.834 ServerApp] 302 GET / (@172.30.6.160) 0.21ms
[I 2025-06-29 17:36:13.834 ServerApp] 302 GET / (@172.30.6.160) 0.21ms
[I 2025-06-29 17:36:13.835 ServerApp] 302 GET / (@172.30.6.160) 0.30ms
[I 2025-06-29 17:36:13.835 ServerApp] 302 GET / (@172.30.6.160) 0.31ms
[I 2025-06-29 17:36:14.282 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.34ms
[I 2025-06-29 17:36:14.282 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.21ms
[I 2025-06-29 17:36:14.282 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.30ms
[I 2025-06-29 17:36:14.282 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.34ms
[I 2025-06-29 17:36:14.283 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.23ms
[W 2025-06-29 17:36:14.671 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.671 ServerApp] 403 GET /api/kernelspecs?1751229374665 (@172.30.6.160) 0.65ms referer=None
[W 2025-06-29 17:36:14.674 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.674 ServerApp] 403 GET /api/kernelspecs?1751229374671 (@172.30.6.160) 0.48ms referer=None
[W 2025-06-29 17:36:14.677 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.677 ServerApp] 403 GET /api/kernelspecs?1751229374674 (@172.30.6.160) 0.84ms referer=None
[W 2025-06-29 17:36:14.681 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.681 ServerApp] 403 GET /api/kernelspecs?1751229374677 (@172.30.6.160) 0.47ms referer=None
[W 2025-06-29 17:36:14.854 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.854 ServerApp] 403 GET /api/kernelspecs?1751229374668 (@172.30.6.160) 0.63ms referer=None
[W 2025-06-29 17:36:14.855 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.855 ServerApp] 403 GET /api/kernels?1751229374667 (@172.30.6.160) 0.79ms referer=None
[W 2025-06-29 17:36:14.855 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.856 ServerApp] 403 GET /api/kernels?1751229374668 (@172.30.6.160) 1.08ms referer=None
[W 2025-06-29 17:36:14.857 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.857 ServerApp] 403 GET /api/kernels?1751229374672 (@172.30.6.160) 0.96ms referer=None
[W 2025-06-29 17:36:14.857 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.857 ServerApp] 403 GET /api/kernels?1751229374675 (@172.30.6.160) 1.25ms referer=None
[W 2025-06-29 17:36:14.857 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.858 ServerApp] 403 GET /api/kernels?1751229374677 (@172.30.6.160) 1.54ms referer=None
[W 2025-06-29 17:36:14.859 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.859 ServerApp] 403 GET /api/kernelspecs?1751229374678 (@172.30.6.160) 1.46ms referer=None
[W 2025-06-29 17:36:14.859 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.860 ServerApp] 403 GET /api/kernels?1751229374678 (@172.30.6.160) 1.75ms referer=None
[W 2025-06-29 17:36:14.861 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.861 ServerApp] 403 GET /api/kernels?1751229374695 (@172.30.6.160) 2.95ms referer=None
[W 2025-06-29 17:36:14.862 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.862 ServerApp] 403 GET /api/sessions?1751229374696 (@172.30.6.160) 3.27ms referer=None
[W 2025-06-29 17:36:14.862 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.862 ServerApp] 403 GET /api/kernels?1751229374697 (@172.30.6.160) 3.56ms referer=None
[W 2025-06-29 17:36:14.864 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.865 ServerApp] 403 GET /api/sessions?1751229374698 (@172.30.6.160) 2.21ms referer=None
[W 2025-06-29 17:36:14.865 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.865 ServerApp] 403 GET /api/kernels?1751229374699 (@172.30.6.160) 2.50ms referer=None
[W 2025-06-29 17:36:14.865 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.865 ServerApp] 403 GET /api/sessions?1751229374699 (@172.30.6.160) 2.80ms referer=None
[W 2025-06-29 17:36:14.866 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.866 ServerApp] 403 GET /api/kernels?1751229374700 (@172.30.6.160) 3.10ms referer=None
[W 2025-06-29 17:36:14.866 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.866 ServerApp] 403 GET /api/sessions?1751229374701 (@172.30.6.160) 3.40ms referer=None
[W 2025-06-29 17:36:14.866 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.867 ServerApp] 403 GET /api/kernels?1751229374702 (@172.30.6.160) 3.69ms referer=None
[W 2025-06-29 17:36:14.867 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.867 ServerApp] 403 GET /api/sessions?1751229374703 (@172.30.6.160) 3.98ms referer=None
[W 2025-06-29 17:36:14.867 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.868 ServerApp] 403 GET /api/kernels?1751229374704 (@172.30.6.160) 4.28ms referer=None
[W 2025-06-29 17:36:14.868 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.868 ServerApp] 403 GET /api/sessions?1751229374705 (@172.30.6.160) 4.58ms referer=None
[W 2025-06-29 17:36:14.881 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.882 ServerApp] 403 GET /api/kernelspecs?1751229374802 (@172.30.6.160) 0.48ms referer=None
[W 2025-06-29 17:36:14.882 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.882 ServerApp] 403 GET /api/kernelspecs?1751229374803 (@172.30.6.160) 0.49ms referer=None
[W 2025-06-29 17:36:14.883 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.883 ServerApp] 403 GET /api/kernelspecs?1751229374804 (@172.30.6.160) 0.60ms referer=None
[W 2025-06-29 17:36:14.883 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:14.884 ServerApp] 403 GET /api/kernelspecs?1751229374805 (@172.30.6.160) 0.88ms referer=None
[W 2025-06-29 17:36:15.604 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.604 ServerApp] 403 GET /api/kernelspecs?1751229374881 (@172.30.6.160) 0.61ms referer=None
[I 2025-06-29 17:36:15.604 ServerApp] 302 GET / (@172.30.6.160) 0.24ms
[I 2025-06-29 17:36:15.605 ServerApp] 302 GET / (@172.30.6.160) 0.23ms
[I 2025-06-29 17:36:15.605 ServerApp] 302 GET / (@172.30.6.160) 0.44ms
[I 2025-06-29 17:36:15.605 ServerApp] 302 GET / (@172.30.6.160) 0.44ms
[I 2025-06-29 17:36:15.696 ServerApp] 302 GET / (@172.30.6.160) 0.17ms
[I 2025-06-29 17:36:15.696 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.49ms
[I 2025-06-29 17:36:15.697 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.55ms
[I 2025-06-29 17:36:15.697 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.59ms
[I 2025-06-29 17:36:15.697 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.63ms
[I 2025-06-29 17:36:15.730 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.18ms
[W 2025-06-29 17:36:15.746 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.746 ServerApp] 403 GET /api/kernelspecs?1751229375742 (@172.30.6.160) 0.48ms referer=None
[W 2025-06-29 17:36:15.748 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.748 ServerApp] 403 GET /api/kernelspecs?1751229375746 (@172.30.6.160) 0.47ms referer=None
[W 2025-06-29 17:36:15.750 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.750 ServerApp] 403 GET /api/kernelspecs?1751229375748 (@172.30.6.160) 0.46ms referer=None
[W 2025-06-29 17:36:15.754 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.754 ServerApp] 403 GET /api/kernelspecs?1751229375750 (@172.30.6.160) 0.56ms referer=None
[W 2025-06-29 17:36:15.790 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.790 ServerApp] 403 GET /api/kernels?1751229375742 (@172.30.6.160) 1.28ms referer=None
[W 2025-06-29 17:36:15.790 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.790 ServerApp] 403 GET /api/kernelspecs?1751229375743 (@172.30.6.160) 1.56ms referer=None
[W 2025-06-29 17:36:15.790 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.791 ServerApp] 403 GET /api/kernels?1751229375743 (@172.30.6.160) 1.89ms referer=None
[W 2025-06-29 17:36:15.791 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.791 ServerApp] 403 GET /api/kernels?1751229375746 (@172.30.6.160) 2.21ms referer=None
[W 2025-06-29 17:36:15.791 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.792 ServerApp] 403 GET /api/kernels?1751229375748 (@172.30.6.160) 2.51ms referer=None
[W 2025-06-29 17:36:15.792 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.792 ServerApp] 403 GET /api/kernelspecs?1751229375751 (@172.30.6.160) 2.85ms referer=None
[W 2025-06-29 17:36:15.792 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.793 ServerApp] 403 GET /api/kernels?1751229375750 (@172.30.6.160) 3.16ms referer=None
[W 2025-06-29 17:36:15.794 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.794 ServerApp] 403 GET /api/kernels?1751229375751 (@172.30.6.160) 1.32ms referer=None
[W 2025-06-29 17:36:15.794 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.794 ServerApp] 403 GET /api/kernels?1751229375753 (@172.30.6.160) 1.61ms referer=None
[W 2025-06-29 17:36:15.795 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.795 ServerApp] 403 GET /api/sessions?1751229375754 (@172.30.6.160) 1.92ms referer=None
[W 2025-06-29 17:36:15.795 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.795 ServerApp] 403 GET /api/kernels?1751229375754 (@172.30.6.160) 2.21ms referer=None
[W 2025-06-29 17:36:15.795 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.796 ServerApp] 403 GET /api/sessions?1751229375755 (@172.30.6.160) 2.51ms referer=None
[W 2025-06-29 17:36:15.796 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.796 ServerApp] 403 GET /api/kernels?1751229375756 (@172.30.6.160) 2.80ms referer=None
[W 2025-06-29 17:36:15.796 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.796 ServerApp] 403 GET /api/sessions?1751229375757 (@172.30.6.160) 3.11ms referer=None
[W 2025-06-29 17:36:15.797 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.797 ServerApp] 403 GET /api/kernels?1751229375758 (@172.30.6.160) 0.80ms referer=None
[W 2025-06-29 17:36:15.798 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.798 ServerApp] 403 GET /api/sessions?1751229375758 (@172.30.6.160) 1.09ms referer=None
[W 2025-06-29 17:36:15.799 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.799 ServerApp] 403 GET /api/kernels?1751229375759 (@172.30.6.160) 1.04ms referer=None
[W 2025-06-29 17:36:15.799 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.799 ServerApp] 403 GET /api/sessions?1751229375760 (@172.30.6.160) 1.32ms referer=None
[W 2025-06-29 17:36:15.800 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.800 ServerApp] 403 GET /api/kernels?1751229375760 (@172.30.6.160) 1.61ms referer=None
[W 2025-06-29 17:36:15.800 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.800 ServerApp] 403 GET /api/sessions?1751229375761 (@172.30.6.160) 1.92ms referer=None
[W 2025-06-29 17:36:15.863 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.863 ServerApp] 403 GET /api/kernelspecs?1751229375770 (@172.30.6.160) 0.49ms referer=None
[W 2025-06-29 17:36:15.864 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.864 ServerApp] 403 GET /api/kernelspecs?1751229375771 (@172.30.6.160) 0.58ms referer=None
[W 2025-06-29 17:36:15.864 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.864 ServerApp] 403 GET /api/kernelspecs?1751229375772 (@172.30.6.160) 0.87ms referer=None
[W 2025-06-29 17:36:15.952 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.952 ServerApp] 403 GET /api/kernelspecs?1751229375772 (@172.30.6.160) 0.88ms referer=None
[W 2025-06-29 17:36:15.962 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:15.962 ServerApp] 403 GET /api/kernelspecs?1751229375868 (@172.30.6.160) 1.00ms referer=None
[I 2025-06-29 17:36:16.114 ServerApp] Connecting to kernel 67e93076-d5db-4f0a-9316-6a69351ef46f.
[I 2025-06-29 17:36:16.320 ServerApp] 302 GET / (@172.30.6.160) 0.47ms
[I 2025-06-29 17:36:16.320 ServerApp] 302 GET / (@172.30.6.160) 0.48ms
[I 2025-06-29 17:36:16.320 ServerApp] 302 GET / (@172.30.6.160) 0.48ms
[I 2025-06-29 17:36:16.320 ServerApp] 302 GET / (@172.30.6.160) 0.47ms
[I 2025-06-29 17:36:16.561 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.46ms
[I 2025-06-29 17:36:16.562 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.63ms
[I 2025-06-29 17:36:16.562 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.67ms
[I 2025-06-29 17:36:16.562 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.71ms
[W 2025-06-29 17:36:16.888 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:16.888 ServerApp] 403 GET /api/kernelspecs?1751229376885 (@172.30.6.160) 0.53ms referer=None
[W 2025-06-29 17:36:16.890 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:16.890 ServerApp] 403 GET /api/kernelspecs?1751229376887 (@172.30.6.160) 0.80ms referer=None
[W 2025-06-29 17:36:16.893 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:16.894 ServerApp] 403 GET /api/kernelspecs?1751229376891 (@172.30.6.160) 0.46ms referer=None
[W 2025-06-29 17:36:16.896 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:16.896 ServerApp] 403 GET /api/kernelspecs?1751229376893 (@172.30.6.160) 0.46ms referer=None
[W 2025-06-29 17:36:17.072 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.072 ServerApp] 403 GET /api/kernels?1751229376886 (@172.30.6.160) 0.55ms referer=None
[W 2025-06-29 17:36:17.073 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.073 ServerApp] 403 GET /api/kernels?1751229376888 (@172.30.6.160) 0.59ms referer=None
[W 2025-06-29 17:36:17.074 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.075 ServerApp] 403 GET /api/kernels?1751229376894 (@172.30.6.160) 1.39ms referer=None
[W 2025-06-29 17:36:17.075 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.075 ServerApp] 403 GET /api/kernels?1751229376892 (@172.30.6.160) 1.68ms referer=None
[W 2025-06-29 17:36:17.075 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.075 ServerApp] 403 GET /api/kernels?1751229376953 (@172.30.6.160) 2.04ms referer=None
[W 2025-06-29 17:36:17.076 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.076 ServerApp] 403 GET /api/sessions?1751229376954 (@172.30.6.160) 2.36ms referer=None
[W 2025-06-29 17:36:17.076 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.076 ServerApp] 403 GET /api/kernels?1751229376955 (@172.30.6.160) 2.65ms referer=None
[W 2025-06-29 17:36:17.076 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.077 ServerApp] 403 GET /api/sessions?1751229376956 (@172.30.6.160) 2.96ms referer=None
[W 2025-06-29 17:36:17.077 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.077 ServerApp] 403 GET /api/kernels?1751229376957 (@172.30.6.160) 3.26ms referer=None
[W 2025-06-29 17:36:17.077 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.078 ServerApp] 403 GET /api/sessions?1751229376958 (@172.30.6.160) 3.56ms referer=None
[W 2025-06-29 17:36:17.078 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.078 ServerApp] 403 GET /api/kernels?1751229376959 (@172.30.6.160) 0.57ms referer=None
[W 2025-06-29 17:36:17.079 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.080 ServerApp] 403 GET /api/sessions?1751229376960 (@172.30.6.160) 0.95ms referer=None
[W 2025-06-29 17:36:17.080 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.080 ServerApp] 403 GET /api/kernelspecs?1751229377008 (@172.30.6.160) 1.25ms referer=None
[W 2025-06-29 17:36:17.080 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.080 ServerApp] 403 GET /api/kernelspecs?1751229377009 (@172.30.6.160) 1.54ms referer=None
[W 2025-06-29 17:36:17.081 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.081 ServerApp] 403 GET /api/kernelspecs?1751229377010 (@172.30.6.160) 1.83ms referer=None
[W 2025-06-29 17:36:17.081 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.081 ServerApp] 403 GET /api/kernelspecs?1751229377011 (@172.30.6.160) 2.14ms referer=None
[I 2025-06-29 17:36:17.143 ServerApp] 302 GET / (@172.30.6.160) 0.15ms
[I 2025-06-29 17:36:17.143 ServerApp] 302 GET / (@172.30.6.160) 0.15ms
[I 2025-06-29 17:36:17.175 ServerApp] 302 GET / (@172.30.6.160) 0.30ms
[I 2025-06-29 17:36:17.175 ServerApp] 302 GET / (@172.30.6.160) 0.31ms
[I 2025-06-29 17:36:17.187 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.21ms
[I 2025-06-29 17:36:17.188 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.54ms
[I 2025-06-29 17:36:17.188 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.54ms
[I 2025-06-29 17:36:17.188 JupyterNotebookApp] 302 GET /tree? (@172.30.6.160) 0.57ms
[W 2025-06-29 17:36:17.197 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.197 ServerApp] 403 GET /api/kernelspecs?1751229377194 (@172.30.6.160) 0.46ms referer=None
[W 2025-06-29 17:36:17.207 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.207 ServerApp] 403 GET /api/kernelspecs?1751229377204 (@172.30.6.160) 0.73ms referer=None
[W 2025-06-29 17:36:17.209 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.210 ServerApp] 403 GET /api/kernelspecs?1751229377207 (@172.30.6.160) 0.45ms referer=None
[W 2025-06-29 17:36:17.212 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.212 ServerApp] 403 GET /api/kernelspecs?1751229377209 (@172.30.6.160) 0.75ms referer=None
[W 2025-06-29 17:36:17.229 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.229 ServerApp] 403 GET /api/kernels?1751229377195 (@172.30.6.160) 0.47ms referer=None
[W 2025-06-29 17:36:17.229 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.230 ServerApp] 403 GET /api/kernels?1751229377197 (@172.30.6.160) 0.46ms referer=None
[W 2025-06-29 17:36:17.243 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.243 ServerApp] 403 GET /api/sessions?1751229377198 (@172.30.6.160) 0.49ms referer=None
[W 2025-06-29 17:36:17.244 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.244 ServerApp] 403 GET /api/kernels?1751229377205 (@172.30.6.160) 0.95ms referer=None
[W 2025-06-29 17:36:17.245 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.245 ServerApp] 403 GET /api/kernels?1751229377207 (@172.30.6.160) 1.25ms referer=None
[W 2025-06-29 17:36:17.245 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.245 ServerApp] 403 GET /api/kernels?1751229377209 (@172.30.6.160) 1.56ms referer=None
[W 2025-06-29 17:36:17.245 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.246 ServerApp] 403 GET /api/kernelspecs?1751229377215 (@172.30.6.160) 1.86ms referer=None
[W 2025-06-29 17:36:17.246 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.246 ServerApp] 403 GET /api/kernels?1751229377216 (@172.30.6.160) 2.17ms referer=None
[W 2025-06-29 17:36:17.247 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.247 ServerApp] 403 GET /api/sessions?1751229377217 (@172.30.6.160) 1.07ms referer=None
[W 2025-06-29 17:36:17.247 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.248 ServerApp] 403 GET /api/kernels?1751229377218 (@172.30.6.160) 1.35ms referer=None
[W 2025-06-29 17:36:17.248 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.248 ServerApp] 403 GET /api/sessions?1751229377219 (@172.30.6.160) 1.64ms referer=None
[W 2025-06-29 17:36:17.248 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.249 ServerApp] 403 GET /api/kernels?1751229377220 (@172.30.6.160) 1.94ms referer=None
[W 2025-06-29 17:36:17.249 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.249 ServerApp] 403 GET /api/sessions?1751229377221 (@172.30.6.160) 2.24ms referer=None
[W 2025-06-29 17:36:17.250 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.250 ServerApp] 403 GET /api/kernelspecs?1751229377232 (@172.30.6.160) 0.57ms referer=None
[W 2025-06-29 17:36:17.250 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.250 ServerApp] 403 GET /api/kernelspecs?1751229377233 (@172.30.6.160) 0.85ms referer=None
[W 2025-06-29 17:36:17.259 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 1846, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/tornado/web.py", line 3363, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/santiagovasquez/miniconda3/envs/test_env/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-06-29 17:36:17.260 ServerApp] 403 GET /api/kernelspecs?1751229377236 (@172.30.6.160) 0.79ms referer=None
